# Используем базовый образ Node.js для сборки
FROM node:18-alpine AS build
WORKDIR /app

# Копируем package.json и package-lock.json для установки зависимостей
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем все файлы проекта и собираем его
COPY ./ ./
RUN npm run build

# Используем минимальный образ NGINX для раздачи собранных файлов
FROM nginx:1.27.2-alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
# Открываем порт для NGINX
EXPOSE 80

# Запускаем NGINX
CMD ["nginx", "-g", "daemon off;"]
