version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - client
      - server
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf 
    networks:
      - my-todos-network

  # Клиентское приложение (React.js)
  client:
    image: andrey522526/my-todos-app:client-v3
    expose:
      - "80"  
    networks:
      - my-todos-network

  # Сервер Node.js
  server:
    image: andrey522526/my-todos-app:servvv  
    expose:
      - "8082" 
    environment:
      POSTGRES_USER: koyeb-adm
      POSTGRES_PASSWORD: rlDEB2V7QCdX
      POSTGRES_DB: todos
      DATABASE_URL: postgres://koyeb-adm:rlDEB2V7QCdX@ep-damp-wave-a22ezu5j.eu-central-1.pg.koyeb.app/todos
    networks:
      - my-todos-network

networks:
  my-todos-network: