services:
  # Сервер Node.js
  server:
    build:
      context: server
      dockerfile: dockerfile
    ports:
      - "8082:8082"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: andrey
      POSTGRES_DB: todos
      DATABASE_URL: postgres://postgres:andrey@db:5432/todos
    depends_on:
      - db

  # Клиент (React.js)
  client:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - server

  # База данных PostgreSQL
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: andrey
      POSTGRES_DB: todos
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - C:/Users/Андрей/Downloads/pg:/backup

# Определение тома для хранения данных PostgreSQL
volumes:
  todos-db-1:
