# Используем базовый образ Node.js
FROM node:16
WORKDIR /app

# Копируем package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем все файлы сервера
COPY ./ ./

# Открываем порт для сервера
EXPOSE 8082

# Запускаем серверное приложение
CMD ["npm", "start"]
